import React, { Fragment, Component } from 'react';
import PropTypes from 'prop-types';
import { withStyles } from '@material-ui/core/styles';
import CssBaseline from '@material-ui/core/CssBaseline';
import Typography from '@material-ui/core/Typography';
import Paper from '@material-ui/core/Paper';
import List from '@material-ui/core/List';
import ListItem from '@material-ui/core/ListItem';
import ListItemText from '@material-ui/core/ListItemText';
import ListSubheader from '@material-ui/core/ListSubheader';
import Avatar from '@material-ui/core/Avatar';
import TextField from '@material-ui/core/TextField';

const styles = theme => ({
    text: {
        paddingTop: theme.spacing.unit * 2,
        paddingLeft: theme.spacing.unit * 2,
        paddingRight: theme.spacing.unit * 2,
    },
    paper: {
        paddingBottom: 50,
    },
    list: {
        marginBottom: theme.spacing.unit * 2,
    },
    subHeader: {
        backgroundColor: theme.palette.background.paper,
    },
    appBar: {
        top: 'auto',
        bottom: 0,
    },
    toolbar: {
        alignItems: 'center',
        justifyContent: 'space-between',
    },
    fabButton: {
        position: 'absolute',
        zIndex: 1,
        top: -30,
        left: 0,
        right: 0,
        margin: '0 auto',
    },
    inputProps: {
        step: 400,
    },
});


const messages = [
    {
        id: 1,
        primary: 'Matthew Mc Conaughey',
        secondary: "What an amazing view ! Looking forward to visit it :D ",
        person: require('../img/profile_pic.png'),
    },
    {
        id: 2,
        primary: 'Brad Pitt',
        secondary: `Do you have a suggestion for a good present for John on his work
        anniversary. I am really confused & would love your thoughts on it.`,
        person: require('../img/profile_pic.png'),
    },
    {
        id: 3,
        primary: 'Mel Gibson',
        secondary: 'I am try out this new BBQ recipe, I think this might be amazing',
        person: require('../img/profile_pic.png'),
    },
    {
        id: 4,
        primary: 'Bradley Cooper',
        secondary: 'I have the tickets to the ReactConf for this year.',
        person: require('../img/profile_pic.png'),
    },
    {
        id: 5,
        primary: "Paul Ntawuruhunga",
        secondary: 'My appointment for the doctor was rescheduled for next Saturday.',
        person: require('../img/profile_pic.png'),
    },
    {
        id: 6,
        primary: 'Miguel Santamaria',
        secondary: `Menus that are generated by the bottom app bar (such as a bottom
        navigation drawer or overflow menu) open as bottom sheets at a higher elevation
        than the bar.`,
        person: require('../img/profile_pic.png'),
    },
    {
        id: 7,
        primary: 'Liechti Sama',
        secondary: `I just got some furniture
        for my backyard and would love to fire up the grill.`,
        person: require('../img/profile_pic.png'),
    },
];

class Comments extends Component {
    constructor(props) {
        super(props);
        this.input = React.createRef();
    }
    render() {
        const { classes } = this.props;
        return (
            <React.Fragment>
                <CssBaseline />
                <Paper square className={classes.paper}>
                    <Typography className={classes.text} variant="h5" gutterBottom>
                        Comments
                    </Typography>
                    <List className={classes.list}>
                        {messages.map(({ id, primary, secondary, person }) => (
                            <Fragment key={id}>
                                {id === 1 && <ListSubheader className={classes.subHeader}>Today</ListSubheader>}
                                {id === 3 && <ListSubheader className={classes.subHeader}>Yesterday</ListSubheader>}
                                <ListItem button>
                                    <Avatar alt="Profile Picture" src={person} />
                                    <ListItemText primary={primary} secondary={secondary} />
                                </ListItem>
                            </Fragment>
                        ))}
                    </List>
                    <Typography className={classes.text} variant="h6" gutterBottom>
                        Add a new comment
                    </Typography>
                    <TextField id="text" type="text" className={classes.inputProps}
                        placeholder="  Go ahead and express your feelings about this content !" multiline={true}
                        rows={2} rowsMax={4} fullWidth={true} />
                </Paper>
            </React.Fragment>
        );
    }
}

Comments.propTypes = {
    classes: PropTypes.object.isRequired,
};

export default withStyles(styles)(Comments);